name: Linting

on:
  push:
    tags:
      - "*"
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  flake8_py3:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 django_saml2_auth_lw/ # run flake8 to source files
